# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `maxHeapSimetrico' in source file `maxHeapSimetrico.m'.
# Generated by Mercury compiler version 22.01-jammy1
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   long deps
#   short deps
#   type_repn self dep
maxHeapSimetrico.optdate maxHeapSimetrico.trans_opt_date maxHeapSimetrico.err maxHeapSimetrico.c_date maxHeapSimetrico.java_date : \
		maxHeapSimetrico.m \
	\
		builtin.int \
		int.int \
		io.int \
		list.int \
		private_builtin.int \
	\
		array.int2 \
		assoc_list.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		map.int2 \
		maybe.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		stream.int2 \
		string.int2 \
		term.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
	\
		maxHeapSimetrico.int

# RULE mh_and_mih_on_c
maxHeapSimetrico.mh maxHeapSimetrico.mih : maxHeapSimetrico.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
maxHeapSimetrico.module_dep : jmercury/maxHeapSimetrico.java

else

# RULE module_dep_on_c
maxHeapSimetrico.module_dep : maxHeapSimetrico.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
maxHeapSimetrico.date maxHeapSimetrico.date0 : \
		maxHeapSimetrico.m \
	\
		builtin.int3 \
		int.int3 \
		io.int3 \
		list.int3 \
		private_builtin.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		map.int3 \
		maybe.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
maxHeapSimetrico.date0 : \
		maxHeapSimetrico.m \
	\
		builtin.int3 \
		int.int3 \
		io.int3 \
		list.int3 \
		private_builtin.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		map.int3 \
		maybe.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE foreign_deps_for_mh
maxHeapSimetrico.$O maxHeapSimetrico.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh

# RULE int0_on_date0
maxHeapSimetrico.int0 : maxHeapSimetrico.date0
	@:

# RULE int_on_date
maxHeapSimetrico.int : maxHeapSimetrico.date
	@:

# RULE int2_on_date
maxHeapSimetrico.int2 : maxHeapSimetrico.date
	@:

# RULE int3_on_date3
maxHeapSimetrico.int3 : maxHeapSimetrico.date3
	@:

# RULE opt_on_opt_date
maxHeapSimetrico.opt : maxHeapSimetrico.optdate
	@:

# RULE trans_opt_on_trans_opt_date
maxHeapSimetrico.trans_opt : maxHeapSimetrico.trans_opt_date
	@:

